DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_BASE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_PIMP';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_BALLAS';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_DOLLAR';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_DIAMOND';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_HATE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_LOVE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_PLAYER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_KING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_KNUCKLE_VARMOD_VAGOS';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SWITCHBLADE_VARMOD_BASE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SWITCHBLADE_VARMOD_VAR1';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SWITCHBLADE_VARMOD_VAR2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_APPISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_APPISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_FLSH';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_SUPP';
DELETE FROM `items` WHERE `name` = 'COMPONENT_APPISTOL_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATPISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATPISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYPISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYPISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYPISTOL_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_VARMOD_BOSS';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_VARMOD_GOON';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SIGHTS';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MACRO_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_COMP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_REVOLVER_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_SUPP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_RAIL';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_FLSH_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_COMP';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_02_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_03_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_04_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_05_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_06_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_07_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_08_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_09_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_10_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL50_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL50_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_SUPP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PISTOL50_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_RAIL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_FLSH_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_PI_COMP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_VINTAGEPISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_VINTAGEPISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTSHOTGUN_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTSHOTGUN_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_FLSH';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_SUPP';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_AFGRIP';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSHOTGUN_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSHOTGUN_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSHOTGUN_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SR_SUPP';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_SMALL_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SR_SUPP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTSMG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTSMG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MACRO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MEDIUM';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_AFGRIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MEDIUM_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MG_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MG_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATMG_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATPDW_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATPDW_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMBATPDW_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_SMALL';
DELETE FROM `items` WHERE `name` = 'COMPONENT_GUSENBERG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_GUSENBERG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MACHINEPISTOL_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MACHINEPISTOL_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MACHINEPISTOL_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_SMALL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MG_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MICROSMG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MICROSMG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MICROSMG_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MINISMG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MINISMG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MACRO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SIGHTS_SMG';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_SMALL_SMG_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SB_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SB_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SMG_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ADVANCEDRIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ADVANCEDRIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_AR_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_VARMOD_LOW';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MACRO_02_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_BP_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_BP_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_CR_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_CR_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMPACTRIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMPACTRIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_COMPACTRIFLE_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MILITARYRIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MILITARYRIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MILITARYRIFLE_SIGHT_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_CLIP_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SC_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SC_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_LARGE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_MAX';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_LARGE_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_NV';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_THERMAL';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MUZZLE_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SR_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SR_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_VARMOD_LUXE';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MRFL_BARREL_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_AT_MRFL_BARREL_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_02';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_03';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_04';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_05';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_06';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_07';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_08';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_09';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_10';
DELETE FROM `items` WHERE `name` = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01';
DELETE FROM `items` WHERE `name` = 'COMPONENT_SNIPERRIFLE_VARMOD_LUXE';

INSERT INTO `items` (`name`, `label`, `limit`) VALUES
('COMPONENT_KNUCKLE_VARMOD_BASE', 'KNUCKLE BASE MODEL', -1),
('COMPONENT_KNUCKLE_VARMOD_PIMP', 'KNUCKLE THE PIMP', -1),
('COMPONENT_KNUCKLE_VARMOD_BALLAS', 'KNUCKLE THE BALLAS', -1),
('COMPONENT_KNUCKLE_VARMOD_DOLLAR', 'KNUCKLE THE HUSTLER', -1),
('COMPONENT_KNUCKLE_VARMOD_DIAMOND', 'KNUCKLE THE ROCK', -1),
('COMPONENT_KNUCKLE_VARMOD_HATE', 'KNUCKLE THE HATER', -1),
('COMPONENT_KNUCKLE_VARMOD_LOVE', 'KNUCKLE THE LOVER', -1),
('COMPONENT_KNUCKLE_VARMOD_PLAYER', 'KNUCKLE THE PLAYER', -1),
('COMPONENT_KNUCKLE_VARMOD_KING', 'KNUCKLE THE KING', -1),
('COMPONENT_KNUCKLE_VARMOD_VAGOS', 'KNUCKLE THE VAGOS', -1),
('COMPONENT_SWITCHBLADE_VARMOD_BASE', 'SWITCHBLADE DEFAULT HANDLE', -1),
('COMPONENT_SWITCHBLADE_VARMOD_VAR1', 'SWITCHBLADE VIP HANDLE', -1),
('COMPONENT_SWITCHBLADE_VARMOD_VAR2', 'SWITCHBLADE BODYGUARD HANDLE', -1),
('COMPONENT_APPISTOL_CLIP_01', 'APPISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_APPISTOL_CLIP_02', 'APPISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_AT_PI_FLSH', 'PISTOL FLASHLIGHT', -1),
('COMPONENT_AT_PI_SUPP', 'PISTOL SUPPRESSOR', -1),
('COMPONENT_APPISTOL_VARMOD_LUXE', 'APPISTOL LUXARY WEAPON FINISH', -1),
('COMPONENT_COMBATPISTOL_CLIP_01', 'COMBATPISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_COMBATPISTOL_CLIP_02', 'COMBATPISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER', 'COMBATPISTOL LUXARY WEAPON FINISH', -1),
('COMPONENT_HEAVYPISTOL_CLIP_01', 'HEAVYPISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_HEAVYPISTOL_CLIP_02', 'HEAVYPISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_HEAVYPISTOL_VARMOD_LUXE', 'HEAVYPISTOL LUXARY WEAPON FINISH', -1),
('COMPONENT_REVOLVER_CLIP_01', 'REVOLVER DEFAULT MAGAZINE', -1),
('COMPONENT_REVOLVER_VARMOD_BOSS', 'REVOLVER VIP FINISH', -1),
('COMPONENT_REVOLVER_VARMOD_GOON', 'REVOLVER BODYGUARD FINISH', -1),
('COMPONENT_REVOLVER_MK2_CLIP_01', 'REVOLVERMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_REVOLVER_MK2_CLIP_TRACER', 'REVOLVERMK2 TRACER AMMO', -1),
('COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY', 'REVOLVERMK2 INCENDIARY AMMO', -1),
('COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT', 'REVOLVERMK2 HOLLOWPOINT AMMO', -1),
('COMPONENT_REVOLVER_MK2_CLIP_FMJ', 'REVOLVERMK2 FMJ AMMO', -1),
('COMPONENT_AT_SIGHTS', 'HOLOGRAPHIC SCOPE', -1),
('COMPONENT_AT_SCOPE_MACRO_MK2', 'SCOPE MACRO MK2', -1),
('COMPONENT_AT_PI_COMP_03', 'REVOLVERMK2 COMPENSATOR', -1),
('COMPONENT_REVOLVER_MK2_CAMO', 'REVOLVERMK2 DIGITAL CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_02', 'REVOLVERMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_03', 'REVOLVERMK2 WOODLAND CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_04', 'REVOLVERMK2 SKULL CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_05', 'REVOLVERMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_06', 'REVOLVERMK2 PERSEUS CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_07', 'REVOLVERMK2 LEOPARD CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_08', 'REVOLVERMK2 ZEBRA CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_09', 'REVOLVERMK2 GEOMETRIC CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_10', 'REVOLVERMK2 BOOM CAMO', -1),
('COMPONENT_REVOLVER_MK2_CAMO_IND_01', 'REVOLVERMK2 PATRIOTIC CAMO', -1),
('COMPONENT_PISTOL_CLIP_01', 'PISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_PISTOL_CLIP_02', 'PISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_AT_PI_SUPP_02', 'PISTOL SUPPRESSOR 2', -1),
('COMPONENT_PISTOL_VARMOD_LUXE', 'PISTOL LUXARY WEAPON FINISH', -1),
('COMPONENT_PISTOL_MK2_CLIP_01', 'PISTOLMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_PISTOL_MK2_CLIP_02', 'PISTOLMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_PISTOL_MK2_CLIP_TRACER', 'PISTOLMK2 TRACER AMMO', -1),
('COMPONENT_PISTOL_MK2_CLIP_INCENDIARY', 'PISTOLMK2 INCENDIARY AMMO', -1),
('COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT', 'PISTOLMK2 HOLLOWPOINT AMMO', -1),
('COMPONENT_PISTOL_MK2_CLIP_FMJ', 'PISTOLMK2 FMJ AMMO', -1),
('COMPONENT_AT_PI_RAIL', 'PISTOLMK2 MOUNTED SCOPE', -1),
('COMPONENT_AT_PI_FLSH_02', 'PISTOLMK2 FLASHLIGHT', -1),
('COMPONENT_AT_PI_COMP', 'PISTOLMK2 COMPENSATOR', -1),
('COMPONENT_PISTOL_MK2_CAMO', 'PISTOLMK2 DIGITAL CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_02', 'PISTOLMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_03', 'PISTOLMK2 WOODLAND CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_04', 'PISTOLMK2 SKULL CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_05', 'PISTOLMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_06', 'PISTOLMK2 PERSEUS CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_07', 'PISTOLMK2 LEOPARD CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_08', 'PISTOLMK2 ZEBRA CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_09', 'PISTOLMK2 GEOMETRIC CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_10', 'PISTOLMK2 BOOM CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_IND_01', 'PISTOLMK2 PATRIOTIC CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_SLIDE', 'PISTOLMK2 DIGITAL SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_02_SLIDE', 'PISTOLMK2 BRUSHSTROKE SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_03_SLIDE', 'PISTOLMK2 WOODLAND SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_04_SLIDE', 'PISTOLMK2 SKULL SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_05_SLIDE', 'PISTOLMK2 SESSANTA NOVE SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_06_SLIDE', 'PISTOLMK2 PERSEUS SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_07_SLIDE', 'PISTOLMK2 LEOPARD SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_08_SLIDE', 'PISTOLMK2 ZEBRA SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_09_SLIDE', 'PISTOLMK2 GEOMETRIC SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_10_SLIDE', 'PISTOLMK2 BOOM SLIDE CAMO', -1),
('COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE', 'PISTOLMK2 PATRIOTIC SLIDE CAMO', -1),
('COMPONENT_PISTOL50_CLIP_01', 'PISTOL50 DEFAULT MAGAZINE', -1),
('COMPONENT_PISTOL50_CLIP_02', 'PISTOL50 EXTENDED MAGAZINE', -1),
('COMPONENT_AT_AR_SUPP_02', 'PISTOL50 SUPPRESSOR', -1),
('COMPONENT_PISTOL50_VARMOD_LUXE', 'PISTOL50 LUXARY WEAPON FINISH', -1),
('COMPONENT_SNSPISTOL_CLIP_01', 'SNSPISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_SNSPISTOL_CLIP_02', 'SNSPISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_SNSPISTOL_VARMOD_LOWRIDER', 'SNSPISTOL LUXARY WEAPON FINISH', -1),
('COMPONENT_SNSPISTOL_MK2_CLIP_01', 'SNSPISTOLMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_SNSPISTOL_MK2_CLIP_02', 'SNSPISTOLMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_SNSPISTOL_MK2_CLIP_TRACER', 'SNSPISTOLMK2 TRACER AMMO', -1),
('COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY', 'SNSPISTOLMK2 INCENDIARY AMMO', -1),
('COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT', 'SNSPISTOLMK2 HOLLOWPOINT AMMO', -1),
('COMPONENT_SNSPISTOL_MK2_CLIP_FMJ', 'SNSPISTOLMK2 FMJ AMMO', -1),
('COMPONENT_AT_PI_RAIL_02', 'SNSPISTOLMK2 MOUNTED SCOPE', -1),
('COMPONENT_AT_PI_FLSH_03', 'SNSPISTOLMK2 FLASHLIGHT', -1),
('COMPONENT_AT_PI_COMP_02', 'SNSPISTOLMK2 COMPENSATOR', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO', 'SNSPISTOLMK2 DIGITAL CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_02', 'SNSPISTOLMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_03', 'SNSPISTOLMK2 WOODLAND CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_04', 'SNSPISTOLMK2 SKULL CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_05', 'SNSPISTOLMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_06', 'SNSPISTOLMK2 PERSEUS CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_07', 'SNSPISTOLMK2 LEOPARD CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_08', 'SNSPISTOLMK2 ZEBRA CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_09', 'SNSPISTOLMK2 GEOMETRIC CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_10', 'SNSPISTOLMK2 BOOM CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_IND_01', 'SNSPISTOLMK2 PATRIOTIC CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE', 'SNSPISTOLMK2 DIGITAL SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE', 'SNSPISTOLMK2 BRUSHSTROKE SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE', 'SNSPISTOLMK2 WOODLAND SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE', 'SNSPISTOLMK2 SKULL SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE', 'SNSPISTOLMK2 SESSANTA NOVE SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE', 'SNSPISTOLMK2 PERSEUS SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE', 'SNSPISTOLMK2 LEOPARD SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE', 'SNSPISTOLMK2 ZEBRA SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE', 'SNSPISTOLMK2 GEOMETRIC SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE', 'SNSPISTOLMK2 BOOM SLIDE CAMO', -1),
('COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE', 'SNSPISTOLMK2 PATRIOTIC SLIDE CAMO', -1),
('COMPONENT_VINTAGEPISTOL_CLIP_01', 'VINTAGEPISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_VINTAGEPISTOL_CLIP_02', 'VINTAGEPISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_ASSAULTSHOTGUN_CLIP_01', 'ASSAULTSHOTGUN DEFAULT MAGAZINE', -1),
('COMPONENT_ASSAULTSHOTGUN_CLIP_02', 'ASSAULTSHOTGUN EXTENDED MAGAZINE', -1),
('COMPONENT_AT_AR_FLSH', 'ASSAULTSHOTGUN FLASHLIGHT', -1),
('COMPONENT_AT_AR_SUPP', 'ASSAULTSHOTGUN SUPPRESSOR', -1),
('COMPONENT_AT_AR_AFGRIP', 'ASSAULTSHOTGUN GRIP', -1),
('COMPONENT_HEAVYSHOTGUN_CLIP_01', 'HEAVYSHOTGUN DEFAULT MAGAZINE', -1),
('COMPONENT_HEAVYSHOTGUN_CLIP_02', 'HEAVYSHOTGUN EXTENDED MAGAZINE', -1),
('COMPONENT_HEAVYSHOTGUN_CLIP_03', 'HEAVYSHOTGUN DRUM MAGAZINE', -1),
('COMPONENT_AT_SR_SUPP', 'PUMPSHOTGUN SUPPRESSOR', -1),
('COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER', 'PUMPSHOTGUN LUXARY WEAPON FINISH', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CLIP_01', 'PUMPSHOTGUNMK2 DEFAULT SHELLS', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY', 'PUMPSHOTGUNMK2 DRAGONS BREATH SHELLS', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING', 'PUMPSHOTGUNMK2 STEEL BUCKSHOT SHELLS', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT', 'PUMPSHOTGUNMK2 FLECHETTE SHELLS', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE', 'PUMPSHOTGUNMK2 EXPLOSIVE SLUG SHELLS', -1),
('COMPONENT_AT_SCOPE_SMALL_MK2', 'PUMPSHOTGUNMK2 MEDIUM SCOPE', -1),
('COMPONENT_AT_SR_SUPP_03', 'PUMPSHOTGUNMK2 SUPPRESSOR', -1),
('COMPONENT_AT_MUZZLE_08', 'PUMPSHOTGUNMK2 SQUARED MUZZLE BRAKE', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO', 'PUMPSHOTGUNMK2 DIGITAL CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_02', 'PUMPSHOTGUNMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_03', 'PUMPSHOTGUNMK2 WOODLAND CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_04', 'PUMPSHOTGUNMK2 SKULL CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_05', 'PUMPSHOTGUNMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_06', 'PUMPSHOTGUNMK2 PERSEUS CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_07', 'PUMPSHOTGUNMK2 LEOPARD CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_08', 'PUMPSHOTGUNMK2 ZEBRA CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_09', 'PUMPSHOTGUNMK2 GEOMETRIC CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_10', 'PUMPSHOTGUNMK2 BOOM CAMO', -1),
('COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01', 'PUMPSHOTGUNMK2 PATRIOTIC CAMO', -1),
('COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE', 'SAWNOFFSHOTGUN LUXARY WEAPON FINISH', -1),
('COMPONENT_ASSAULTSMG_CLIP_01', 'ASSAULTSMG DEFAULT MAGAZINE', -1),
('COMPONENT_ASSAULTSMG_CLIP_02', 'ASSAULTSMG EXTENDED MAGAZINE', -1),
('COMPONENT_AT_SCOPE_MACRO', 'ASSAULTSMG MOUNTED SCOPE', -1),
('COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER', 'ASSAULTSMG LUXARY WEAPON FINISH', -1),
('COMPONENT_COMBATMG_CLIP_01', 'COMBATMG DEFAULT MAGAZINE', -1),
('COMPONENT_COMBATMG_CLIP_02', 'COMBATMG EXTENDED MAGAZINE', -1),
('COMPONENT_AT_SCOPE_MEDIUM', 'COMBATMG MOUNTED SCOPE', -1),
('COMPONENT_COMBATMG_VARMOD_LOWRIDER', 'COMBATMG LUXARY WEAPON FINISH', -1),
('COMPONENT_COMBATMG_MK2_CLIP_01', 'COMBATMGMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_COMBATMG_MK2_CLIP_02', 'COMBATMGMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_COMBATMG_MK2_CLIP_TRACER', 'COMBATMGMK2 TRACER AMMO', -1),
('COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY', 'COMBATMGMK2 INCENDIARY AMMO', -1),
('COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING', 'COMBATMGMK2 HOLLOWPOINT AMMO', -1),
('COMPONENT_COMBATMG_MK2_CLIP_FMJ', 'COMBATMGMK2 FMJ AMMO', -1),
('COMPONENT_AT_AR_AFGRIP_02', 'COMBATMGMK2 GRIP', -1),
('COMPONENT_AT_SCOPE_MEDIUM_MK2', 'COMBATMGMK2 LARGE SCOPE', -1),
('COMPONENT_AT_MUZZLE_01', 'COMBATMGMK2 FLAT MUZZLE BRAKE', -1),
('COMPONENT_AT_MUZZLE_02', 'COMBATMGMK2 TACTICAL MUZZLE BRAKE', -1),
('COMPONENT_AT_MUZZLE_03', 'COMBATMGMK2 FAT-END MUZZLE BRAKE', -1),
('COMPONENT_AT_MUZZLE_04', 'COMBATMGMK2 PRECISION MUZZLE BRAKE', -1),
('COMPONENT_AT_MUZZLE_05', 'COMBATMGMK2 HEAVY DUTY MUZZLE BRAKE', -1),
('COMPONENT_AT_MUZZLE_06', 'COMBATMGMK2 SLANTED MUZZLE BRAKE', -1),
('COMPONENT_AT_MUZZLE_07', 'COMBATMGMK2 SPLIT-END MUZZLE BRAKE', -1),
('COMPONENT_AT_MG_BARREL_01', 'COMBATMGMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_MG_BARREL_02', 'COMBATMGMK2 HEAVY BARREL', -1),
('COMPONENT_COMBATMG_MK2_CAMO', 'COMBATMGMK2 DIGITAL CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_02', 'COMBATMGMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_03', 'COMBATMGMK2 WOODLAND CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_04', 'COMBATMGMK2 SKULL CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_05', 'COMBATMGMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_06', 'COMBATMGMK2 PERSEUS CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_07', 'COMBATMGMK2 LEOPARD CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_08', 'COMBATMGMK2 ZEBRA CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_09', 'COMBATMGMK2 GEOMETRIC CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_10', 'COMBATMGMK2 BOOM CAMO', -1),
('COMPONENT_COMBATMG_MK2_CAMO_IND_01', 'COMBATMGMK2 PATRIOTIC CAMO', -1),
('COMPONENT_COMBATPDW_CLIP_01', 'COMBATPDW DEFAULT MAGAZINE', -1),
('COMPONENT_COMBATPDW_CLIP_02', 'COMBATPDW EXTENDED MAGAZINE', -1),
('COMPONENT_COMBATPDW_CLIP_03', 'COMBATPDW DRUM MAGAZINE', -1),
('COMPONENT_AT_SCOPE_SMALL', 'COMBATPDW MOUNTED SCOPE', -1),
('COMPONENT_GUSENBERG_CLIP_01', 'GUSENBERG DEFAULT MAGAZINE', -1),
('COMPONENT_GUSENBERG_CLIP_02', 'GUSENBERG EXTENDED MAGAZINE', -1),
('COMPONENT_MACHINEPISTOL_CLIP_01', 'MACHINEPISTOL DEFAULT MAGAZINE', -1),
('COMPONENT_MACHINEPISTOL_CLIP_02', 'MACHINEPISTOL EXTENDED MAGAZINE', -1),
('COMPONENT_MACHINEPISTOL_CLIP_03', 'MACHINEPISTOL DRUM MAGAZINE', -1),
('COMPONENT_MG_CLIP_01', 'MG DEFAULT MAGAZINE', -1),
('COMPONENT_MG_CLIP_02', 'MG EXTENDED MAGAZINE', -1),
('COMPONENT_AT_SCOPE_SMALL_02', 'MG MOUNTED SCOPE', -1),
('COMPONENT_MG_VARMOD_LOWRIDER', 'MG LUXARY WEAPON FINISH', -1),
('COMPONENT_MICROSMG_CLIP_01', 'MICROSMG DEFAULT MAGAZINE', -1),
('COMPONENT_MICROSMG_CLIP_02', 'MICROSMG EXTENDED MAGAZINE', -1),
('COMPONENT_MICROSMG_VARMOD_LUXE', 'MICROSMG LUXARY WEAPON FINISH', -1),
('COMPONENT_MINISMG_CLIP_01', 'MINISMG DEFAULT MAGAZINE', -1),
('COMPONENT_MINISMG_CLIP_02', 'MINISMG EXTENDED MAGAZINE', -1),
('COMPONENT_SMG_CLIP_01', 'SMG DEFAULT MAGAZINE', -1),
('COMPONENT_SMG_CLIP_02', 'SMG EXTENDED MAGAZINE', -1),
('COMPONENT_SMG_CLIP_03', 'SMG DRUM MAGAZINE', -1),
('COMPONENT_AT_SCOPE_MACRO_02', 'SMG MOUNTED SCOPE', -1),
('COMPONENT_SMG_VARMOD_LUXE', 'SMG LUXARY WEAPON FINISH', -1),
('COMPONENT_SMG_MK2_CLIP_01', 'SMGMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_SMG_MK2_CLIP_02', 'SMGMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_SMG_MK2_CLIP_TRACER', 'SMGMK2 TRACER AMMO', -1),
('COMPONENT_SMG_MK2_CLIP_INCENDIARY', 'SMGMK2 INCENDIARY AMMO', -1),
('COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT', 'SMGMK2 HOLLOWPOINT AMMO', -1),
('COMPONENT_SMG_MK2_CLIP_FMJ', 'SMGMK2 FMJ AMMO', -1),
('COMPONENT_AT_SIGHTS_SMG', 'SMGMK2 HOLOGRAPHIC SCOPE', -1),
('COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2', 'SMGMK2 SMALL SCOPE', -1),
('COMPONENT_AT_SCOPE_SMALL_SMG_MK2', 'SMGMK2 MEDIUM SCOPE', -1),
('COMPONENT_AT_SB_BARREL_01', 'SMGMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_SB_BARREL_02', 'SMGMK2 HEAVY BARREL', -1),
('COMPONENT_SMG_MK2_CAMO', 'SMGMK2 DIGITAL CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_02', 'SMGMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_03', 'SMGMK2 WOODLAND CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_04', 'SMGMK2 SKULL CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_05', 'SMGMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_06', 'SMGMK2 PERSEUS CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_07', 'SMGMK2 LEOPARD CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_08', 'SMGMK2 ZEBRA CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_09', 'SMGMK2 GEOMETRIC CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_10', 'SMGMK2 BOOM CAMO', -1),
('COMPONENT_SMG_MK2_CAMO_IND_01', 'SMGMK2 PATRIOTIC CAMO', -1),
('COMPONENT_ADVANCEDRIFLE_CLIP_01', 'ADVANCEDRIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_ADVANCEDRIFLE_CLIP_02', 'ADVANCEDRIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE', 'ADVANCEDRIFLE LUXARY WEAPON FINISH', -1),
('COMPONENT_ASSAULTRIFLE_CLIP_01', 'ASSAULTRIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_ASSAULTRIFLE_CLIP_02', 'ASSAULTRIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_ASSAULTRIFLE_CLIP_03', 'ASSAULTRIFLE DRUM MAGAZINE', -1),
('COMPONENT_ASSAULTRIFLE_VARMOD_LUXE', 'ASSAULTRIFLE LUXARY WEAPON FINISH', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CLIP_01', 'ASSAULTRIFLEMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CLIP_02', 'ASSAULTRIFLEMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER', 'ASSAULTRIFLEMK2 TRACER AMMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY', 'ASSAULTRIFLEMK2 INCENDIARY AMMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING', 'ASSAULTRIFLEMK2 ARMOR PIERCING AMMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ', 'ASSAULTRIFLEMK2 FMJ AMMO', -1),
('COMPONENT_AT_AR_BARREL_01', 'ASSAULTRIFLEMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_AR_BARREL_02', 'ASSAULTRIFLEMK2 HEAVY BARREL', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO', 'ASSAULTRIFLEMK2 DIGITAL CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_02', 'ASSAULTRIFLEMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_03', 'ASSAULTRIFLEMK2 WOODLAND CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_04', 'ASSAULTRIFLEMK2 SKULL CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_05', 'ASSAULTRIFLEMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_06', 'ASSAULTRIFLEMK2 PERSEUS CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_07', 'ASSAULTRIFLEMK2 LEOPARD CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_08', 'ASSAULTRIFLEMK2 ZEBRA CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_09', 'ASSAULTRIFLEMK2 GEOMETRIC CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_10', 'ASSAULTRIFLEMK2 BOOM CAMO', -1),
('COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01', 'ASSAULTRIFLEMK2 PATRIOTIC CAMO', -1),
('COMPONENT_BULLPUPRIFLE_CLIP_01', 'BULLPUPRIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_BULLPUPRIFLE_CLIP_02', 'BULLPUPRIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_BULLPUPRIFLE_VARMOD_LOW', 'BULLPUPRIFLE LUXARY WEAPON FINISH', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CLIP_01', 'BULLPUPRIFLEMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CLIP_02', 'BULLPUPRIFLEMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER', 'BULLPUPRIFLEMK2 TRACER AMMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY', 'BULLPUPRIFLEMK2 INCENDIARY AMMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING', 'BULLPUPRIFLEMK2 ARMOR PIERCING AMMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ', 'BULLPUPRIFLEMK2 FMJ AMMO', -1),
('COMPONENT_AT_SCOPE_MACRO_02_MK2', 'BULLPUPRIFLEMK2 SMALL SCOPE', -1),
('COMPONENT_AT_BP_BARREL_01', 'BULLPUPRIFLEMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_BP_BARREL_02', 'BULLPUPRIFLEMK2 HEAVY BARREL', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO', 'BULLPUPRIFLEMK2 DIGITAL CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_02', 'BULLPUPRIFLEMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_03', 'BULLPUPRIFLEMK2 WOODLAND CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_04', 'BULLPUPRIFLEMK2 SKULL CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_05', 'BULLPUPRIFLEMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_06', 'BULLPUPRIFLEMK2 PERSEUS CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_07', 'BULLPUPRIFLEMK2 LEOPARD CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_08', 'BULLPUPRIFLEMK2 ZEBRA CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_09', 'BULLPUPRIFLEMK2 GEOMETRIC CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_10', 'BULLPUPRIFLEMK2 BOOM CAMO', -1),
('COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01', 'BULLPUPRIFLEMK2 PATRIOTIC CAMO', -1),
('COMPONENT_CARBINERIFLE_CLIP_01', 'CARBINERIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_CARBINERIFLE_CLIP_02', 'CARBINERIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_CARBINERIFLE_CLIP_03', 'CARBINERIFLE BOX MAGAZINE', -1),
('COMPONENT_CARBINERIFLE_VARMOD_LUXE', 'CARBINERIFLE LUXARY WEAPON FINISH', -1),
('COMPONENT_CARBINERIFLE_MK2_CLIP_01', 'CARBINERIFLEMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_CARBINERIFLE_MK2_CLIP_02', 'CARBINERIFLEMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER', 'CARBINERIFLEMK2 TRACER AMMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY', 'CARBINERIFLEMK2 INCENDIARY AMMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING', 'CARBINERIFLEMK2 ARMOR PIERCING AMMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ', 'CARBINERIFLEMK2 FMJ AMMO', -1),
('COMPONENT_AT_CR_BARREL_01', 'CARBINERIFLEMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_CR_BARREL_02', 'CARBINERIFLEMK2 HEAVY BARREL', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO', 'CARBINERIFLEMK2 DIGITAL CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_02', 'CARBINERIFLEMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_03', 'CARBINERIFLEMK2 WOODLAND CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_04', 'CARBINERIFLEMK2 SKULL CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_05', 'CARBINERIFLEMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_06', 'CARBINERIFLEMK2 PERSEUS CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_07', 'CARBINERIFLEMK2 LEOPARD CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_08', 'CARBINERIFLEMK2 ZEBRA CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_09', 'CARBINERIFLEMK2 GEOMETRIC CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_10', 'CARBINERIFLEMK2 BOOM CAMO', -1),
('COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01', 'CARBINERIFLEMK2 PATRIOTIC CAMO', -1),
('COMPONENT_COMPACTRIFLE_CLIP_01', 'COMPACTRIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_COMPACTRIFLE_CLIP_02', 'COMPACTRIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_COMPACTRIFLE_CLIP_03', 'COMPACTRIFLE DRUM MAGAZINE', -1),
('COMPONENT_MILITARYRIFLE_CLIP_01', 'MILITARYRIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_MILITARYRIFLE_CLIP_02', 'MILITARYRIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_MILITARYRIFLE_SIGHT_01', 'MILITARYRIFLE IRONSIGHTS', -1),
('COMPONENT_SPECIALCARBINE_CLIP_01', 'SPECIALCARBINE DEFAULT MAGAZINE', -1),
('COMPONENT_SPECIALCARBINE_CLIP_02', 'SPECIALCARBINE EXTENDED MAGAZINE', -1),
('COMPONENT_SPECIALCARBINE_CLIP_03', 'SPECIALCARBINE DRUM MAGAZINE', -1),
('COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER', 'SPECIALCARBINE LUXARY WEAPON FINISH', -1),
('COMPONENT_SPECIALCARBINE_MK2_CLIP_01', 'SPECIALCARBINEMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_SPECIALCARBINE_MK2_CLIP_02', 'SPECIALCARBINEMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER', 'SPECIALCARBINEMK2 TRACER AMMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY', 'SPECIALCARBINEMK2 INCENDIARY AMMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING', 'SPECIALCARBINEMK2 ARMOR PIERCING AMMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ', 'SPECIALCARBINEMK2 FMJ AMMO', -1),
('COMPONENT_AT_SC_BARREL_01', 'SPECIALCARBINEMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_SC_BARREL_02', 'SPECIALCARBINEMK2 HEAVY BARREL', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO', 'SPECIALCARBINEMK2 DIGITAL CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_02', 'SPECIALCARBINEMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_03', 'SPECIALCARBINEMK2 WOODLAND CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_04', 'SPECIALCARBINEMK2 SKULL CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_05', 'SPECIALCARBINEMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_06', 'SPECIALCARBINEMK2 PERSEUS CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_07', 'SPECIALCARBINEMK2 LEOPARD CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_08', 'SPECIALCARBINEMK2 ZEBRA CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_09', 'SPECIALCARBINEMK2 GEOMETRIC CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_10', 'SPECIALCARBINEMK2 BOOM CAMO', -1),
('COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01', 'SPECIALCARBINEMK2 PATRIOTIC CAMO', -1),
('COMPONENT_AT_SCOPE_LARGE', 'HEAVYSNIPER MOUNTED SCOPE', -1),
('COMPONENT_AT_SCOPE_MAX', 'HEAVYSNIPER ADVANCED SCOPE', -1),
('COMPONENT_HEAVYSNIPER_MK2_CLIP_01', 'HEAVYSNIPERMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_HEAVYSNIPER_MK2_CLIP_02', 'HEAVYSNIPERMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY', 'HEAVYSNIPERMK2 INCENDIARY AMMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING', 'HEAVYSNIPERMK2 ARMOR PIERCING AMMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ', 'HEAVYSNIPERMK2 FMJ AMMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE', 'HEAVYSNIPERMK2 ARMOR PIERCING INCENDIARY AMMO', -1),
('COMPONENT_AT_SCOPE_LARGE_MK2', 'HEAVYSNIPERMK2 SCOPE ZOOM', -1),
('COMPONENT_AT_SCOPE_NV', 'HEAVYSNIPERMK2 SCOPE NIGHTVISION', -1),
('COMPONENT_AT_SCOPE_THERMAL', 'HEAVYSNIPERMK2 SCOPE THERMAL', -1),
('COMPONENT_AT_MUZZLE_09', 'HEAVYSNIPERMK2 MUZZLE BELL', -1),
('COMPONENT_AT_SR_BARREL_01', 'HEAVYSNIPERMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_SR_BARREL_02', 'HEAVYSNIPERMK2 HEAVY BARREL', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO', 'HEAVYSNIPERMK2 DIGITAL CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_02', 'HEAVYSNIPERMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_03', 'HEAVYSNIPERMK2 WOODLAND CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_04', 'HEAVYSNIPERMK2 SKULL CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_05', 'HEAVYSNIPERMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_06', 'HEAVYSNIPERMK2 PERSEUS CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_07', 'HEAVYSNIPERMK2 LEOPARD CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_08', 'HEAVYSNIPERMK2 ZEBRA CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_09', 'HEAVYSNIPERMK2 GEOMETRIC CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_10', 'HEAVYSNIPERMK2 BOOM CAMO', -1),
('COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01', 'HEAVYSNIPERMK2 PATRIOTIC CAMO', -1),
('COMPONENT_MARKSMANRIFLE_CLIP_01', 'MARKSMANRIFLE DEFAULT MAGAZINE', -1),
('COMPONENT_MARKSMANRIFLE_CLIP_02', 'MARKSMANRIFLE EXTENDED MAGAZINE', -1),
('COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM', 'MARKSMANRIFLE MOUNTED SCOPE', -1),
('COMPONENT_MARKSMANRIFLE_VARMOD_LUXE', 'MARKSMANRIFLE LUXARY WEAPON FINISH', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CLIP_01', 'MARKSMANRIFLEMK2 DEFAULT MAGAZINE', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CLIP_02', 'MARKSMANRIFLEMK2 EXTENDED MAGAZINE', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER', 'MARKSMANRIFLEMK2 TRACER AMMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY', 'MARKSMANRIFLEMK2 INCENDIARY AMMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING', 'MARKSMANRIFLEMK2 ARMOR PIERCING AMMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ', 'MARKSMANRIFLEMK2 FMJ AMMO', -1),
('COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2', 'MARKSMANRIFLEMK2 SCOPE ZOOM', -1),
('COMPONENT_AT_MRFL_BARREL_01', 'MARKSMANRIFLEMK2 DEFAULT BARREL', -1),
('COMPONENT_AT_MRFL_BARREL_02', 'MARKSMANRIFLEMK2 HEAVY BARREL', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO', 'MARKSMANRIFLEMK2 DIGITAL CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_02', 'MARKSMANRIFLEMK2 BRUSHSTROKE CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_03', 'MARKSMANRIFLEMK2 WOODLAND CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_04', 'MARKSMANRIFLEMK2 SKULL CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_05', 'MARKSMANRIFLEMK2 SESSANTA NOVE CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_06', 'MARKSMANRIFLEMK2 PERSEUS CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_07', 'MARKSMANRIFLEMK2 LEOPARD CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_08', 'MARKSMANRIFLEMK2 ZEBRA CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_09', 'MARKSMANRIFLEMK2 GEOMETRIC CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_10', 'MARKSMANRIFLEMK2 BOOM CAMO', -1),
('COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01', 'MARKSMANRIFLEMK2 PATRIOTIC CAMO', -1),
('COMPONENT_SNIPERRIFLE_VARMOD_LUXE', 'SNIPERRIFLE LUXARY WEAPON FINISH', -1);